---
- hosts: prod-webserver
  remote_user: airdoc
  become: yes
  become_user: root
  tasks:
    - name: copy the webserver api code
      copy: src=../../eye.tar.gz dest=/home/airdoc/eye.tar.gz
    - name: copy the php library code
      copy: src=../../phplib.tar.gz dest=/home/airdoc/phplib.tar.gz
    - name: copy the html code
      copy: src=../../dist.tar.gz dest=/home/airdoc/dist.tar.gz
    - name: copy the wechat code
      copy: src=../../wechat-dist.tar.gz dest=/home/airdoc/wechat-dist.tar.gz
    - name: uncompress the files
      shell: tar xzvf /home/airdoc/eye.tar.gz
    - name: uncompress the files
      shell: tar xzvf /home/airdoc/phplib.tar.gz
    - name: uncompress the files
      shell: tar xzvf /home/airdoc/dist.tar.gz
    - name: uncompress the files
      shell: tar xzvf /home/airdoc/wechat-dist.tar.gz
    - name: copy the file into the dest
      shell: cp -rf /home/airdoc/phplib /var/www
    - name: copy the file into the dest
      shell: cp -rf /home/airdoc/eye    /var/www
    - name: copy the file into the dest
      shell: cp -rf /home/airdoc/dist    /var/www/eye
    - name: copy the file into the dest
      shell: cp -rf /home/airdoc/crm-dist/* /var/www/eye/crm-dist
    - name: create the link
      shell: rm -rf /var/www/eye/config/config && ln -sf /var/www/eye/config/production /var/www/eye/config/config
    - name: copy the redis template
      template: src="./config/eye/prod/Redis.class.php.j2" dest="/var/www/eye/config/production/Redis.class.php"
    - name: copy the config tempalte
      template: src="./config/eye/prod/config.inc.php.j2" dest="/var/www/eye/config/production/config.inc.php"
    - name: remove the default nginx configuration
      shell: rm -rf /etc/nginx/conf.d/default.conf
    - name: write the nginx config file
      template: src="./config/nginx/nginx.conf.j2" dest="/etc/nginx/nginx.conf"
      notify:
      - restart nginx
    - name: write the nginx config file
      template: src="./config/nginx/conf.d/prod/mtc.airdoc.com.conf.j2" dest="/etc/nginx/conf.d/mtc.airdoc.com.conf"
      notify:
      - restart nginx
    - name: write the nginx config file
      template: src="./config/nginx/conf.d/prod/aiscreening.airdoc.com.conf.j2" dest="/etc/nginx/conf.d/aiscreening.airdoc.com.conf"
      notify:
      - restart nginx
    - name: write the nginx config file
      template: src="./config/nginx/conf.d/prod/sti.airdoc.com.conf.j2" dest="/etc/nginx/conf.d/sti.airdoc.com.conf"
      notify:
      - restart nginx
    - name: write the nginx config file
      template: src="./config/nginx/conf.d/prod/doctor-crm.airdoc.com.conf.j2" dest="/etc/nginx/conf.d/doctor-crm.airdoc.com.conf"
      notify:
      - restart nginx
    - name: write the nginx config file
      template: src="./config/nginx/conf.d/prod/wj.airdoc.com.conf.j2" dest="/etc/nginx/conf.d/wj.airdoc.com.conf"
      notify:
      - restart nginx
    - name: write the nginx config file
      template: src="./config/nginx/conf.d/prod/open-api.airdoc.com.conf.j2" dest="/etc/nginx/conf.d/open-api.airdoc.com.conf"
      notify:
      - restart nginx
    - name: write the nginx config file
      template: src="./config/nginx/conf.d/prod/s.airdoc.com.conf.j2" dest="/etc/nginx/conf.d/s.airdoc.com.conf"
      notify:
      - restart nginx
    - name: write the nginx config file
      template: src="./config/nginx/conf.d/prod/crm.airdoc.com.conf.j2" dest="/etc/nginx/conf.d/crm.airdoc.com.conf"
      notify:
      - restart nginx
    - name: write the nginx config file
      template: src="./config/nginx/conf.d/prod/eye.airdoc.com.conf.j2" dest="/etc/nginx/conf.d/eye.airdoc.com.conf"
      notify:
      - restart nginx
    - name: write the nginx config file
      template: src="./config/nginx/conf.d/prod/yp.airdoc.com.conf.j2" dest="/etc/nginx/conf.d/yp.airdoc.com.conf"
      notify:
      - restart nginx
    - name: write the nginx config file
      template: src="./config/nginx/conf.d/prod/eye-admin.airdoc.com.conf.j2" dest="/etc/nginx/conf.d/eye-admin.airdoc.com.conf"
      notify:
      - restart nginx
    - name: write the nginx config file
      template: src="./config/nginx/conf.d/prod/ant.airdoc.com.conf.j2" dest="/etc/nginx/conf.d/ant.airdoc.com.conf"
      notify:
      - restart nginx
    - name: write the php-fpm config file
      copy: src="./config/php-fpm/epro.conf" dest="/etc/php-fpm.d/epro.conf"
    - name: write the php-fpm config file
      copy: src="./config/php-fpm/eye.conf" dest="/etc/php-fpm.d/eye.conf"
    - name: write the php-fpm config file
      copy: src="./config/php-fpm/open.conf" dest="/etc/php-fpm.d/open.conf"
    - name: write the php-fpm config file
      copy: src="./config/php-fpm/www.conf" dest="/etc/php-fpm.d/www.conf"
    - name: ensure nginx is running
      service: name=nginx state=started
    - name: ensure php-fpm is running
      service: name=php-fpm state=started
    - name: check the airlog stat
      stat: path=/var/log/airlog
      register: stat_result
    - name: create log directory
      file: path=/var/log/airlog mode=0755 state=directory owner=apache
      when: stat_result.stat.exists == False
    - name: clean files
      shell: rm -rf /home/airdoc/*.gz /home/airdoc/eye /home/airdoc/crm-dist /home/airdoc/dist /home/airdoc/phplib
  handlers:
    - name: restart nginx
      service: name=nginx state=restarted
    - name: restart php-fpm
      service: name=php-fpm state=restarted
